### ISSUE TITLE
Getting BufferUnderflowException when previewing a layer from geoserver

### ISSUE THREAD

**Issue by viggyprabhu** [ngageoint/geowave#279]
I ingested data from the geowave-example, SimpleIngest.java. Then to view it from geoserver 2.6.1, I created a new geowave datastore in geoserver and gave the instance name and zookeeper server parameters. I was able to create the datastore and also create a new layer 'point'. However when I tried to preview the layer as OpenLayers, I am getting the error, Rendering process failed on the map. And the following exception on the console:

Caused by: java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:506)
        at java.nio.HeapByteBuffer.getDouble(HeapByteBuffer.java:514)
        at mil.nga.giat.geowave.store.adapter.statistics.BoundingBoxDataStatistics.fromBinary(BoundingBoxDataStatistics.java:95)
        at mil.nga.giat.geowave.index.PersistenceUtils.fromBinary(PersistenceUtils.java:92)
        at mil.nga.giat.geowave.accumulo.metadata.AbstractAccumuloPersistence.entryToValue(AbstractAccumuloPersistence.java:345)
        at mil.nga.giat.geowave.accumulo.metadata.AccumuloDataStatisticsStore.entryToValue(AccumuloDataStatisticsStore.java:142)
        at mil.nga.giat.geowave.accumulo.metadata.AccumuloDataStatisticsStore.entryToValue(AccumuloDataStatisticsStore.java:34)
        at mil.nga.giat.geowave.accumulo.metadata.AbstractAccumuloPersistence.getObject(AbstractAccumuloPersistence.java:307)
        at mil.nga.giat.geowave.accumulo.metadata.AccumuloDataStatisticsStore.getDataStatistics(AccumuloDataStatisticsStore.java:133)
        at mil.nga.giat.geowave.vector.plugin.GeoWaveDataStoreComponents.getDataStatistics(GeoWaveDataStoreComponents.java:98)
        at mil.nga.giat.geowave.vector.plugin.GeoWaveFeatureReader.clipIndexedBBOXConstraints(GeoWaveFeatureReader.java:482)
        at mil.nga.giat.geowave.vector.plugin.GeoWaveFeatureCollection.getBBox(GeoWaveFeatureCollection.java:336)
        at mil.nga.giat.geowave.vector.plugin.GeoWaveFeatureCollection.openIterator(GeoWaveFeatureCollection.java:232)
        at org.geotools.data.store.DataFeatureCollection.iterator(DataFeatureCollection.java:198)
        at org.geotools.data.store.DataFeatureCollection.features(DataFeatureCollection.java:187)
        at org.geotools.data.store.DataFeatureCollection.features(DataFeatureCollection.java:78)
        at org.geotools.renderer.lite.StreamingRenderer.drawPlain(StreamingRenderer.java:2335)
        at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2061)
        at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:820)
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:491)
        ... 100 more

**Comment by chrisbennight** [comment]
Are you able to generate a test case that can replicate this?  I put something together that should run through the same process
https://github.com/ngageoint/geowave/pull/281/files
(load data, generate WMS request) and wasn't able to duplicate this.

Even if it's not structured as a formal test, if you have a project handy that can do this that would be helpful.

**Comment by viggyprabhu** [comment]
@rfecher had suggested "Regarding the buffer underflow, can you be certain that the code for geowave that you ingested data with matches the one in GeoServer WEB-INF/lib. There was a change earlier this week on 0.8.4-SNAPSHOT that may effect compatibility.". I checked this and the code is the same. I tried again by deleting all data, ingesting again using SimpleIngest and then building the geoserver-singlejar by running 'mvn install -Pgeotools-container-singlejar'. I still get the same exception.
Regarding the test, I will first have to understand the format of the xml, will spend sometime on it and see if I can come up with it. Meanwhile if you want something to be tested manually, let me know. I am able to reproduce this everytime.

**Comment by chrisbennight** [comment]
@spohnan was able to replicate this on a single node cluster manually - just need to turn it into a test we can replicate (and ensure is fixed)

**Comment by spohnan** [comment]
A rookie mistake on my part sent @rfecher on a wild goose chase ... sorry. I had a configuration issue that caused the cluster to pick up an old version of the Accumulo iterator. Per the recommendation above, once I ensured that all versions match everything works as expected.

**Comment by spohnan** [comment]
@viggyprabhu can you still reproduce the error after re-ingesting data as @rfecher suggested? I thought I was able to reproduce the problem but it was data ingested from a previous version.

**Comment by nishchalgautam** [comment]
I am sorry but I finally found what the issue was. I had not configured my accumulo installation to work with geowave. After I followed the instruction given [here](http://ngageoint.github.io/geowave/documentation.html#overview-5), I am not getting the BufferUnderflowException and able to add the Layers. However now I am getting the following error when the map is getting rendered in geoserver. 

2015-04-01 02:36:57,843 [tserver.TabletServer] WARN : exception while doing multi-scan
java.lang.NoClassDefFoundError: Could not initialize class org.geotools.factory.FactoryCreator
        at org.geotools.factory.CommonFactoryFinder.getServiceRegistry(CommonFactoryFinder.java:76)
        at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:346)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:300)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:317)
        at org.geotools.filter.text.commons.AbstractCompilerFactory.makeCompiler(AbstractCompilerFactory.java:55)
        at org.geotools.filter.text.commons.CompilerUtil.parseFilter(CompilerUtil.java:195)
        at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:120)
        at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:99)
        at mil.nga.giat.geowave.vector.query.CqlQueryFilterIterator.init(CqlQueryFilterIterator.java:223)
        at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:253)
        at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:223)

Looks like I am missing Geotools library in Accumulo path. Will try to fix this and update it here. For now, this issue can be closed as not a bug.

**Comment by viggyprabhu** [comment]
I am sorry but I finally found what the issue was. I had not configured my accumulo installation to work with geowave. After I followed the instruction given [here](https://ngageoint.github.io/geowave/documentation.html#overview-5), I am not getting the BufferUnderflowException and able to add the Layers. However now I am getting the following error when the map is getting rendered in geoserver.

2015-04-01 02:36:57,843 [tserver.TabletServer] WARN : exception while doing multi-scan
java.lang.NoClassDefFoundError: Could not initialize class org.geotools.factory.FactoryCreator
at org.geotools.factory.CommonFactoryFinder.getServiceRegistry(CommonFactoryFinder.java:76)
at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:346)
at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:300)
at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:317)
at org.geotools.filter.text.commons.AbstractCompilerFactory.makeCompiler(AbstractCompilerFactory.java:55)
at org.geotools.filter.text.commons.CompilerUtil.parseFilter(CompilerUtil.java:195)
at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:120)
at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:99)
at mil.nga.giat.geowave.vector.query.CqlQueryFilterIterator.init(CqlQueryFilterIterator.java:223)
at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:253)
at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:223)

Looks like I am missing Geotools library in Accumulo path. Will try to fix this and update it here. For now, this issue can be closed as not a bug.

**Comment by saddam1997** [comment]
hello guy's
I am facing same issue but in nxt project pls help me...
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:412)
	at nxt.Attachment$ColoredCoinsAssetIssuance.<init>(Attachment.java:988)
	at nxt.TransactionType$ColoredCoins$1.parseAttachment(TransactionType.java:1506)
	at nxt.TransactionType$ColoredCoins$1.parseAttachment(TransactionType.java:1463)
	at nxt.TransactionImpl.newTransactionBuilder(TransactionImpl.java:686)
	at nxt.TransactionImpl.newTransactionBuilder(TransactionImpl.java:734)
	at nxt.UnconfirmedTransaction.<init>(UnconfirmedTransaction.java:51)
	at nxt.TransactionProcessorImpl$2.load(TransactionProcessorImpl.java:68)
	at nxt.TransactionProcessorImpl$2.load(TransactionProcessorImpl.java:64)
	at nxt.db.EntityDbTable.lambda$getManyBy$0(EntityDbTable.java:258)
	at nxt.db.DbIterator.next(DbIterator.java:68)
